start_date: 2024-01-01
end_date: 2026-12-31

universe:
  - TLT-US
  - IEI-US
  - SHY-US
  - BIL-US
  - SLV-US
  - GLD-US
  - USO-US
  - UNG-US
  - SPY-US
  - INDA-US
  - IBIT-US
  - ETHA-US
  - VIXY-US

model_state_features:
  - close_momentum_10
  - close_momentum_20
  - close_momentum_30
  - close_momentum_60
  - close_momentum_90
  - close_momentum_120
  - close_momentum_240

models:
  - TLT_AMMA
  - IEI_AMMA
  - SHY_AMMA
  - BIL_AMMA
  - SLV_AMMA
  - GLD_AMMA
  - SPY_AMMA
  - INDA_AMMA
  - IBIT_AMMA
  - ETHA_AMMA

aggregators:
  - model_mvo_amma_constrained

optimizers:
  - mean_variance_constrained

execution_portfolio: mean_variance_constrained
cash_buffer: 0.005

ib_gateway:
  host: 127.0.0.1
  port: 4004
  client_id: 21
  flex_web_token: ""
  nav_flex_query_id: ""
  fund_inception_date: 2025-10-15

notifications:
  msteams_webhook: ""
